apps/crud/models.py
from datetime import datetime


from apps.app import db
from werkzeug.security import generate_password_hash


class User(db.Model):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, index=True)
    email = db.Column(db.String, index=True, unique=True)
    password_hash = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)

    @property
    def password(self):
        raise AttributeError("password is not a readable attribute")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, length


class UserForm(FlaskForm):
    username = StringField(
        "Username",
        validators=[
            DataRequired(message="Username is required"),
            length(max=30, message="Username must be less than 30 characters"),
        ],
    )
    email = StringField(
        "Email",
        validators=[
            DataRequired(message="Email is required"),
            Email(message="Email is invalid"),
        ],
    )
    password = PasswordField(
        "password",
        validators=[
            DataRequired(message="Password is required"),
        ],
    )
    submit = SubmitField("Submit")

apps/crud/__init__.py
import apps.crud.models

apps/crud/views.py
from flask import Blueprint, redirect, render_template, url_for
from apps.app import db
from apps.crud.forms import UserForm
from apps.crud.models import User

crud = Blueprint("crud", __name__, template_folder="templates", static_folder="static")


@crud.route("/")
def index():
    return render_template("crud/index.html")


@crud.route("/sql")
def sql():
    db.session.query(User).all()
    return "check your console log"


@crud.route("/users/new", methods=["GET", "POST"])
def create_user():
    form = UserForm()
    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
        )
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("crud.users"))
    return render_template("crud/create.html", form=form)


@crud.route("/users")
def users():
    users = User.query.all()
    return render_template("crud/index.html", users=users)


@crud.route("/users/<user_id>", methods=["GET", "POST"])
def edit_user(user_id):
    form = UserForm()
    user = User.query.filter_by(id=user_id).first()

    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("crud.users"))
    return render_template("crud/edit.html", form=form, user=user)


@crud.route("/users/<user_id>/delete", methods=["POST"])
def delete_user(user_id):
    user = User.query.filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("crud.users"))

apps/crud/templates/crud/create.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <title>Create new user</title>
  </head>

  <body>
    <h2>Create new user</h2>
    <form
      action="{{url_for('crud.create_user')}}"
      method="POST"
      novalidate="novalidate"
    >
      {{form.csrf_token}}
      <p>{{form.username.label}} {{form.username(placeholder="Username")}}</p>
      {% for error in form.username.errors %}
      <span style="color: red">{{error}}</span>
      {% endfor %}
      <p>{{form.email.label}}{{form.email(placeholder="Email")}}</p>
      {% for error in form.email.errors %}
      <span style="color: red">{{error}}</span>
      {% endfor %}
      <p>{{form.password.label}}{{form.password(placeholder="Password")}}</p>
      {% for error in form.password.errors %}
      <span style="color: red">{{error}}</span>
      {% endfor %}
      <p>{{form.submit()}}</p>
    </form>
  </body>
</html>

apps/crud/templates/crud/edit.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <title>Edit User</title>
    <link
      rel="stylesheet"
      href="{{url_for('crud.static', filename='style.css')}}"
    />
  </head>

  <body>
    <h2>Edit User</h2>
    <form
      action="{{url_for('crud.edit_user', user_id=user.id)}}"
      method="POST"
      novalidate="novalidate"
    >
      {{form.csrf_token}}
      <p>{{form.username.label}}{{form.username(placeholder="Username")}}</p>
      {%for error in form.username.erros %}
      <span style="color: red">{{error}}</span>
      {%endfor%}
      <p>{{form.email.label}}{{form.email(placeholder="Email")}}</p>
      {%for error in form.email.erros %}
      <span style="color: red">{{error}}</span>
      {%endfor%}
      <p>{{form.password.label}}{{form.password(placeholder="Password")}}</p>
      {%for error in form.password.erros %}
      <span style="color: red">{{error}}</span>
      {%endfor%}
      <p><input type="submit" value="Apply change" /></p>
    </form>

    <form action = "{{url_for('crud.delete_user', user_id=user.id)}}" method="POST">
      {{form.csrf_token}}
      <input type="submit" value="Delete User" />
    </form>

  </body>
</html>

apps/crud/templates/crud/index.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <title>Users</title>
    <link
      rel="stylesheet"
      ,
      href="{{url_for('crud.static', filename='style.css')}}"/>
  </head>

  <body>
    <h2>User view</h2>

    <a href="{{url_for('crud.create_user')}}">Create new user</a>

    <table>
      <tr>
        <th>User ID</th>
        <th>Username</th>
        <th>Email</th>
      </tr>
      {% for user in users %}
      <tr>
        <td>
          <a href="{{url_for('crud.edit_user', user_id=user.id)}}">{{user.id}}</a>
        </td>
        <td>{{user.username}}</td>
        <td>{{user.email}}</td>
      </tr>
      {% endfor %}
  </body>
</html>